name: Build WAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B -q clean package -DskipTests
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuxeo-client-war
          path: target2/*.war
